image: python:3.6

before_script:
    - echo '*** Set necessary proxies so this machine can access Internet ***'
    - export http_proxy="http://exflwgs06.desy.de:3128/"
    - export https_proxy="http://exflwgs06.desy.de:3128/"
    - pip install pytest
    - pip install future
    - pip install .

unittest:
    script:
    # Do unit tests
    - make test

