image: python:3.6

before_script:
    - echo '*** Set necessary proxies so this machine can access Internet ***'
    - export http_proxy="http://exflwgs06.desy.de:3128/"
    - export https_proxy="http://exflwgs06.desy.de:3128/"
    - apt update
    - apt -y install xvfb
    - apt -y install qt5-default
    - pip install git+https://github.com/European-XFEL/karabo_data.git
    - pip install pytest
    - pip install future
    - pip install .
    - export DISPLAY=:99.0
    - start-stop-daemon --start -b -x /usr/bin/Xvfb $DISPLAY

unittest:
    script:
    # Do unit tests
    - make test

