language: python
dist: xenial
services:
  - xvfb

addons:
  apt:
    packages:
      - qt5-default

python:
  - "3.7"
  - "3.6"
  - "3.5"

install:
  - pip install 'pyqt5<5.13'
  - make install

script:
  - make test

