#!/home/unimelb.edu.au/mbergemann/.anaconda3/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'geoAssembler==0.1.0','gui_scripts','geoAssemblerGui'
__requires__ = 'geoAssembler==0.1.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('geoAssembler==0.1.0', 'gui_scripts', 'geoAssemblerGui')()
    )
