version: 2
jobs:
  build:
    docker:
      - image: ghcr.io/european-xfel/geoassembler-testing:latest
    steps:
      - checkout

      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "setup.py" }}-py38
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip setuptools
            pip install -e '.[test]'
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "setup.py" }}-py38
          paths:
            - "venv"
      - run:
          command: xvfb-run venv/bin/pytest -v
          environment:
            QT_DEBUG_PLUGINS: 1
