name: Build Image using Dockerfile
on: [push]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Publish Image
      uses: matootie/github-docker@v3.1.0
      with:
        accessToken: ${{ secrets.GITHUB_TOKEN }}
        imageName: geoAssembler-testing
        context: .circleci/
        containerRegistry: true
